apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: model-serving
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - api
  - worker-ocr
  - redis
  - mysql
  - ingress.yaml
