apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-ocr-batch
  namespace: model-serving
  labels:
    app: worker-ocr-batch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-ocr-batch
  template:
    metadata:
      labels:
        app: worker-ocr-batch
    spec:
      containers:
        - name: worker-ocr-batch
          image: model-serving-worker-ocr:latest
          envFrom:
            - configMapRef:
                name: worker-ocr-batch-config
            - secretRef:
                name: model-serving-secret
                optional: true
