apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Uncomment to enable network policies
# resources:
#   - default-deny.yaml
#   - allow-ingress-to-api.yaml
#   - allow-kafka-mysql-redis.yaml
