apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: model-serving
resources:
  - ../../../base
patches:
  - path: patch-api-replicas.yaml
  - path: patch-worker-replicas.yaml
  - path: patch-resources.yaml
