apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: model-serving
resources:
  - ../../../base
  - ../../../base/worker-ocr-batch
patches:
  - path: patch-worker-batch-config.yaml
  - path: patch-worker-resources.yaml
