apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: model-serving
resources:
  - ../../../base
  - ../../../base/writer
patches:
  - path: patch-add-writer.yaml
  - path: patch-affinity.yaml
  - path: patch-hpa.yaml
